{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnsl.secretName" . }}
  labels:
    {{- include "cnsl.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existing := lookup "v1" "Secret" .Release.Namespace (include "cnsl.secretName" .) }}
  {{- $jwtSecret := .Values.secrets.jwtSecret }}
  {{- if not $jwtSecret }}
    {{- if $existing }}
      {{- $jwtSecret = index $existing.data "jwt-secret" | b64dec }}
    {{- else }}
      {{- $jwtSecret = randAlphaNum 48 }}
    {{- end }}
  {{- end }}
  {{- $apiSecret := .Values.secrets.apiSecret }}
  {{- if not $apiSecret }}
    {{- if $existing }}
      {{- $apiSecret = index $existing.data "api-secret" | b64dec }}
    {{- else }}
      {{- $apiSecret = randAlphaNum 48 }}
    {{- end }}
  {{- end }}
  jwt-secret: {{ $jwtSecret | b64enc }}
  api-secret: {{ $apiSecret | b64enc }}
{{- end }}